Repository CZERTAINLY/CZERTAINLY-Auth, pull requests merged in 2023-03, with the labels that each got.

#39 Add user identification endpoint
  src/Czertainly.Auth/Controllers/UsersController.cs
  src/Czertainly.Auth/Services/IUserService.cs
  src/Czertainly.Auth/Services/UserService.cs
Labels: enhancement

#40 Add health checks
  src/Czertainly.Auth/Program.cs
Labels: enhancement, ignore-for-release

#41 Release version 1.1.0
  .github/workflows/codeql.yml
  Dockerfile
  README.md
  docker/entry.sh
  docker/update-cacerts.sh
  src/Czertainly.Auth/Controllers/UsersController.cs
  src/Czertainly.Auth/Czertainly.Auth.csproj
  src/Czertainly.Auth/Program.cs
  src/Czertainly.Auth/Services/IUserService.cs
  src/Czertainly.Auth/Services/UserService.cs
Labels: ignore-for-release

#42 Release version 1.1.0
  src/Czertainly.Auth/Czertainly.Auth.csproj
Labels: ignore-for-release
